### ISSUE TITLE
Filter all users and then compare in code is not a good choice

### ISSUE THREAD

**Issue by quynhlv** [TranTriDat/DjangoPractice#1]
https://github.com/TranTriDat/DjangoPractice/blob/5b0dddd3772941ec2867a7797c7f5bbcc35aa9ac/User/tasks.py#L25

- Why don't we use filter()?
- Need to learn more about:

`
for user in all_users:
    ....
`

And

`
for user in all_users.iterator():
    ....
`

**Comment by TranTriDat** [comment]
Anh ơi em có thử filter và làm trên 1 nhánh mới, nếu được nhờ anh review giúp em ạ:
https://github.com/TranTriDat/DjangoPractice/pull/6

**Comment by TranTriDat** [comment]
Anh ơi em làm lại 1 request mới với thêm iterator vào for và bỏ all khi xài filter, nếu được nhờ anh review giúp em ạ:
https://github.com/TranTriDat/DjangoPractice/pull/7
