### ISSUE TITLE
Khi add Product ma co nhieu category thi se add the nao? Data JSON frontend goi len ntn?

### ISSUE THREAD

**Issue by quynhlv** [TranTriDat/DjangoPractice#5]
https://github.com/TranTriDat/DjangoPractice/blob/5b0dddd3772941ec2867a7797c7f5bbcc35aa9ac/Catalog/api/serializers.py#L33

**Comment by TranTriDat** [comment]
Anh ơi em đã sửa lại phần add product của API, nếu được thì anh review giúp em, em có để mẫu JSON khi up lên trong pull request luôn:
https://github.com/TranTriDat/DjangoPractice/pull/8
